project: # https://quarto.org/docs/manuscripts/
  type: manuscript # Specifies this project is a manuscript format.
  output-dir: docs # Directory where the rendered output files will be placed.
  render:
    - "!adm/" # Exclude the 'adm' directory and its contents from rendering.
    - "!renv/" # Exclude the 'renv' directory and its contents from rendering.
    - "!docker/" # Exclude the 'docker' directory and its contents from rendering.

execute: # https://quarto.org/docs/computations/execution-options.html
  freeze: auto # Automatically manage code execution based on changes
  cache: true # Enable caching of code chunks to speed up rendering on subsequent runs
  warning: false # Prevent R code chunk warnings from appearing in the output.
  message: false # Prevent R code chunk messages from appearing in the output.
  echo: false # Do not include the R code chunks in Article.

manuscript: # https://quarto.org/docs/manuscripts/authoring/rstudio.html
  article: index.qmd # Main manuscript file.
  meca-bundle: false # Generate MECA bundle for journal submission.
  notebooks:
    - notebook: Scripts/ProcessingScripts/01_procedural.qmd
      title: "Exclusões procedimentais"
    - notebook: Scripts/ProcessingScripts/02_posthoc.qmd
      title: "Indicadores post hoc C/IER"
    - notebook: Scripts/ProcessingScripts/03_vif.qmd
      title: "Multicolinearidade VIF"

bibliography: references.bib # https://quarto.org/docs/authoring/citations.html
# File containing the bibliographic references in BibTeX format.
csl: apa7ed.csl # Citation Style Language: see others at https://www.zotero.org/styles

format: # https://quarto.org/docs/reference/formats/html.html
  html:
    theme: spacelab # A clean, modern theme for HTML output.
    toc: true # Include a table of contents in the HTML output.
    comments:
      hypothesis: true # Enable Hypothesis comments in the HTML output.
  docx: default # Use the default Word template for DOCX output.
  pdf: default # Use the default LaTeX template for PDF output.

editor: source # Sets the default editor mode to source.
